### ISSUE TITLE
Error occurs when create rabbitmq machines

### ISSUE THREAD

**Issue by vincentstchu** [DevOpsOneself/Vagrant-ansible#4]
==> rabbitmq: Box 'CentOS7' could not be found. Attempting to find and install...
    rabbitmq: Box Provider: virtualbox
    rabbitmq: Box Version: >= 0
==> rabbitmq: Box file was not detected as metadata. Adding it directly...
==> rabbitmq: Adding box 'CentOS7' (v0) for provider: virtualbox
    rabbitmq: Downloading: CentOS7
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/vince/git/Vagrant-ansible/CentOS7
<img width="594" alt="image" src="https://user-images.githubusercontent.com/24803055/45306738-f9a23080-b54f-11e8-8d2b-32d55d8053a9.png">

**Comment by vincentstchu** [comment]
Changing "CentOS7" to "centos/7" in nodes.yaml may solve the problem

**Comment by GavinliSH** [comment]
@vincentstchu yes, you can find [vagrant box](https://app.vagrantup.com/boxes/search) here. In my environment the box named 'CentOS7'.
`vagrant box [box_name] [box_url]`
